print('Welcome to the Tip Calculator made by "Rishi Soni"')
amount = input("Give your total amount here:")
amount = float(amount)
tip_percent = input("How much would be the tip in the form of pecentage of total bill, you want to give?10, 12 or 15? ")
tip_percent = int(tip_percent)
peoples = input("Amoung how many pepole you want to split the bill: ")
peoples = int(peoples)
total_bill = amount + ((amount/100)*tip_percent)
print(total_bill)
bill_per_head = (round(total_bill/peoples, 2))
print(f"Each person should pay: ₹{bill_per_head}")